// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2QspGFwKw0QihK5rpC23HeAyvL8wtMUY',
    appId: '1:404561864253:web:9f7d1c4e3028127bb12c54',
    messagingSenderId: '404561864253',
    projectId: 'messenger-flutter-464a7',
    authDomain: 'messenger-flutter-464a7.firebaseapp.com',
    storageBucket: 'messenger-flutter-464a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkMQw5nRvS3W1bLFLWo6-DAD3a1xxZWg',
    appId: '1:404561864253:android:b10b62edf6cb018ab12c54',
    messagingSenderId: '404561864253',
    projectId: 'messenger-flutter-464a7',
    storageBucket: 'messenger-flutter-464a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjR02mlmPsTOPULZDAy12idAq72AJztzw',
    appId: '1:404561864253:ios:0e2eb5084227bec5b12c54',
    messagingSenderId: '404561864253',
    projectId: 'messenger-flutter-464a7',
    storageBucket: 'messenger-flutter-464a7.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjR02mlmPsTOPULZDAy12idAq72AJztzw',
    appId: '1:404561864253:ios:5d1dd37999bc2450b12c54',
    messagingSenderId: '404561864253',
    projectId: 'messenger-flutter-464a7',
    storageBucket: 'messenger-flutter-464a7.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
